/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "MarketData": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MyLinkableValue": {
      "foo": string
      "type": "sst.sst.Linkable"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}